INFO:root:Бот стартовал
INFO:root:Бот стартовал
INFO:root:Бот стартовал
INFO:root:Бот стартовал
INFO:root:Бот стартовал
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/classified/telegrambot/matchbot.py", line 35, in welcome
    checkuser()
TypeError: checkuser() missing 2 required positional arguments: 'update' and 'context'
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:root:Бот стартовал
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/classified/telegrambot/matchbot.py", line 36, in welcome
    checkuser()
TypeError: checkuser() missing 2 required positional arguments: 'update' and 'context'
INFO:root:Пользователь Classified перешел в заполнению анкеты
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/conversationhandler.py", line 626, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/classified/telegrambot/matchbot.py", line 67, in adduser
    return NAME
NameError: name 'NAME' is not defined
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/classified/telegrambot/matchbot.py", line 36, in welcome
    checkuser()
TypeError: checkuser() missing 2 required positional arguments: 'update' and 'context'
INFO:root:Пользователь Classified перешел в заполнению анкеты
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/conversationhandler.py", line 626, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/classified/telegrambot/matchbot.py", line 67, in adduser
    return NAME
NameError: name 'NAME' is not defined
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/classified/telegrambot/matchbot.py", line 37, in welcome
    checkuser()
TypeError: checkuser() missing 2 required positional arguments: 'update' and 'context'
INFO:root:Пользователь Classified перешел в заполнению анкеты
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/classified/telegrambot/matchbot.py", line 37, in welcome
    checkuser()
TypeError: checkuser() missing 2 required positional arguments: 'update' and 'context'
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/classified/telegrambot/matchbot.py", line 37, in welcome
    checkuser()
TypeError: checkuser() missing 2 required positional arguments: 'update' and 'context'
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/classified/telegrambot/matchbot.py", line 37, in welcome
    checkuser(update, context)
  File "/home/classified/telegrambot/matchbot.py", line 48, in checkuser
    adduser()
TypeError: adduser() missing 2 required positional arguments: 'update' and 'context'
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:root:Пользователь Classified перешел в заполнению анкеты
ERROR:telegram.ext.updater:Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/updater.py", line 646, in _network_loop_retry
    if not action_cb():
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/updater.py", line 597, in polling_action_cb
    updates = self.bot.get_updates(
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/ext/extbot.py", line 224, in get_updates
    updates = super().get_updates(
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/bot.py", line 3054, in get_updates
    self._post(
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/home/classified/telegrambot/venv/lib/python3.9/site-packages/telegram/utils/request.py", line 283, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
INFO:apscheduler.scheduler:Scheduler has been shut down
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:root:Пользователь Classified перешел в заполнению анкеты
INFO:root:Пользователь Classified перешел в заполнению анкеты
